language: php
 
php: 7.1
 
before_script:
    - composer install
 
notifications:
    email:
        recipients:
            - example@example.com
        on_success: never
        on_failure: always
